
<!DOCTYPE HTML>
<html lang='fr'>
<head>
	<title>Blog</title>
	<meta charset='utf-8'>
	<link rel='stylesheet' href='views/main.css'/>
</head>

<body>
		
		
		<header>
		
			<h1>Bienvenue sur mon super BLOG</h1> 
        <nav>
            <ul>
				<?php $userSession = new UserSession(); ?>
            	<?php if ($userSession->isAuthenticated()): ?>
				
            	    <li>Bonjour <em><?=$userSession->getUserName();?></em> </li>
            	    <li><a href="index.php?p=signout">Déconnexion</a></li>
        		<?php else: ?>
            		<li><a href="index.php?p=signup">Créer un compte</a></li>
            		<li><a href="index.php?p=signin">Connexion</a></li>
            	<?php endif; ?>
					<li><a href='index.php?p=home'>Accueil</a></li>
					
        	</ul>
        </nav>
			
			
		</header>
		<section>
		<?php include $page.'.phtml';?>
	
		</section>
		
</body>
</html>
					
					
					
					
	
	
		


	




	

	
	
	
